name: dawaey_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1  # تمت إضافته هنا

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^14.1.1
  intl: ^0.18.1
  sqflite: ^2.3.2
  path: ^1.8.3
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true